# Generated by Django 4.0.3 on 2022-07-23 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_remove_category_slug_en_remove_category_slug_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_uz',
        ),
    ]
